package com.jk.model;

/**
 * 商品详情表
 */
public class GoodsAndDetails {
    /**
     * 商品详情id
     * This field corresponds to the database column t_goods_details.goods_details_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsDetailsId;

    /**
     * 产地
     * This field corresponds to the database column t_goods_details.goods_area
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsArea;

    /**
     * 存储条件
     * This field corresponds to the database column t_goods_details.goods_save
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsSave;

    /**
     * 净含量
     * This field corresponds to the database column t_goods_details.goods_ml
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsMl;

    /**
     * 品牌
     * This field corresponds to the database column t_goods_details.goods_brand
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsBrand;

    /**
     * 商品介绍(长图)
     * This field corresponds to the database column t_goods_details.goods_introduce
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsIntroduce;

    /**
     * 商品id
     * This field corresponds to the database column t_goods_details.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_details_id
     *
     * @return the value of t_goods_details.goods_details_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsDetailsId() {
        return goodsDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_details_id
     *
     * @param goodsDetailsId the value for t_goods_details.goods_details_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsDetailsId(String goodsDetailsId) {
        this.goodsDetailsId = goodsDetailsId == null ? null : goodsDetailsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_area
     *
     * @return the value of t_goods_details.goods_area
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsArea() {
        return goodsArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_area
     *
     * @param goodsArea the value for t_goods_details.goods_area
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsArea(String goodsArea) {
        this.goodsArea = goodsArea == null ? null : goodsArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_save
     *
     * @return the value of t_goods_details.goods_save
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsSave() {
        return goodsSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_save
     *
     * @param goodsSave the value for t_goods_details.goods_save
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsSave(String goodsSave) {
        this.goodsSave = goodsSave == null ? null : goodsSave.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_ml
     *
     * @return the value of t_goods_details.goods_ml
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsMl() {
        return goodsMl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_ml
     *
     * @param goodsMl the value for t_goods_details.goods_ml
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsMl(String goodsMl) {
        this.goodsMl = goodsMl == null ? null : goodsMl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_brand
     *
     * @return the value of t_goods_details.goods_brand
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsBrand() {
        return goodsBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_brand
     *
     * @param goodsBrand the value for t_goods_details.goods_brand
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsBrand(String goodsBrand) {
        this.goodsBrand = goodsBrand == null ? null : goodsBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_introduce
     *
     * @return the value of t_goods_details.goods_introduce
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsIntroduce() {
        return goodsIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_introduce
     *
     * @param goodsIntroduce the value for t_goods_details.goods_introduce
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsIntroduce(String goodsIntroduce) {
        this.goodsIntroduce = goodsIntroduce == null ? null : goodsIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_details.goods_id
     *
     * @return the value of t_goods_details.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_details.goods_id
     *
     * @param goodsId the value for t_goods_details.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }
}