package com.jk.model;

/**
 * 商品规格中间表
 */
public class GoodsAndSpecification {
    /**
     * 商品规格中间表  id
     * This field corresponds to the database column t_goods_specification.goods_specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsSpecificationId;

    /**
     * 商品表
     * This field corresponds to the database column t_goods_specification.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * 规格参数表id
     * This field corresponds to the database column t_goods_specification.specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String specificationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specification.goods_specification_id
     *
     * @return the value of t_goods_specification.goods_specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsSpecificationId() {
        return goodsSpecificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specification.goods_specification_id
     *
     * @param goodsSpecificationId the value for t_goods_specification.goods_specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsSpecificationId(String goodsSpecificationId) {
        this.goodsSpecificationId = goodsSpecificationId == null ? null : goodsSpecificationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specification.goods_id
     *
     * @return the value of t_goods_specification.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specification.goods_id
     *
     * @param goodsId the value for t_goods_specification.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specification.specification_id
     *
     * @return the value of t_goods_specification.specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSpecificationId() {
        return specificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specification.specification_id
     *
     * @param specificationId the value for t_goods_specification.specification_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSpecificationId(String specificationId) {
        this.specificationId = specificationId == null ? null : specificationId.trim();
    }
}