package com.jk.model;

/**
 * 标签表
 */
public class Label {
    /**
     * 标签表id
     * This field corresponds to the database column t_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String labelId;

    /**
     * 标签名称
     * This field corresponds to the database column t_label.label_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String labelName;

    /**
     * 标签说明
     * This field corresponds to the database column t_label.label_info
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String labelInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.label_id
     *
     * @return the value of t_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.label_id
     *
     * @param labelId the value for t_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId == null ? null : labelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.label_name
     *
     * @return the value of t_label.label_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.label_name
     *
     * @param labelName the value for t_label.label_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.label_info
     *
     * @return the value of t_label.label_info
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getLabelInfo() {
        return labelInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.label_info
     *
     * @param labelInfo the value for t_label.label_info
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setLabelInfo(String labelInfo) {
        this.labelInfo = labelInfo == null ? null : labelInfo.trim();
    }
}