package com.jk.model;

import java.util.Date;

/**
 * 广告表
 */
public class Advertising {
    /**
     * 广告id
     * This field corresponds to the database column t_advertising.advertising _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String advertisingId;

    /**
     * 广告名称
     * This field corresponds to the database column t_advertising.advertising _name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String advertisingName;

    /**
     * 广告链接
     * This field corresponds to the database column t_advertising.advertising _link
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String advertisingLink;

    /**
     * 广告位id
     * This field corresponds to the database column t_advertising.adPositionId_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String adpositionidId;

    /**
     * 有效时间
     * This field corresponds to the database column t_advertising.valid_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date validTime;

    /**
     * 点击数
     * This field corresponds to the database column t_advertising.hits
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer hits;

    /**
     * 广告图片
     * This field corresponds to the database column t_advertising.advertising_img
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String advertisingImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.advertising _id
     *
     * @return the value of t_advertising.advertising _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getAdvertisingId() {
        return advertisingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.advertising _id
     *
     * @param advertisingId the value for t_advertising.advertising _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAdvertisingId(String advertisingId) {
        this.advertisingId = advertisingId == null ? null : advertisingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.advertising _name
     *
     * @return the value of t_advertising.advertising _name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getAdvertisingName() {
        return advertisingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.advertising _name
     *
     * @param advertisingName the value for t_advertising.advertising _name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAdvertisingName(String advertisingName) {
        this.advertisingName = advertisingName == null ? null : advertisingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.advertising _link
     *
     * @return the value of t_advertising.advertising _link
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getAdvertisingLink() {
        return advertisingLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.advertising _link
     *
     * @param advertisingLink the value for t_advertising.advertising _link
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAdvertisingLink(String advertisingLink) {
        this.advertisingLink = advertisingLink == null ? null : advertisingLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.adPositionId_id
     *
     * @return the value of t_advertising.adPositionId_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getAdpositionidId() {
        return adpositionidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.adPositionId_id
     *
     * @param adpositionidId the value for t_advertising.adPositionId_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAdpositionidId(String adpositionidId) {
        this.adpositionidId = adpositionidId == null ? null : adpositionidId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.valid_time
     *
     * @return the value of t_advertising.valid_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.valid_time
     *
     * @param validTime the value for t_advertising.valid_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.hits
     *
     * @return the value of t_advertising.hits
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.hits
     *
     * @param hits the value for t_advertising.hits
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertising.advertising_img
     *
     * @return the value of t_advertising.advertising_img
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getAdvertisingImg() {
        return advertisingImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertising.advertising_img
     *
     * @param advertisingImg the value for t_advertising.advertising_img
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAdvertisingImg(String advertisingImg) {
        this.advertisingImg = advertisingImg == null ? null : advertisingImg.trim();
    }
}