package com.jk.model;

import java.util.Date;

/**
 * 评论表
 */
public class Comment {
    /**
     * 评论id
     * This field corresponds to the database column t_comment.comment_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String commentId;

    /**
     * 商品id
     * This field corresponds to the database column t_comment.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * .用户id
     * This field corresponds to the database column t_comment.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userId;

    /**
     * 评论时间
     * This field corresponds to the database column t_comment.comment_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date commentDate;

    /**
     * 评论详情
     * This field corresponds to the database column t_comment.comment_details
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String commentDetails;

    /**
     * 评分 1-5
     * This field corresponds to the database column t_comment.score
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_id
     *
     * @return the value of t_comment.comment_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_id
     *
     * @param commentId the value for t_comment.comment_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.goods_id
     *
     * @return the value of t_comment.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.goods_id
     *
     * @param goodsId the value for t_comment.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.user_id
     *
     * @return the value of t_comment.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.user_id
     *
     * @param userId the value for t_comment.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_date
     *
     * @return the value of t_comment.comment_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_date
     *
     * @param commentDate the value for t_comment.comment_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_details
     *
     * @return the value of t_comment.comment_details
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getCommentDetails() {
        return commentDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_details
     *
     * @param commentDetails the value for t_comment.comment_details
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setCommentDetails(String commentDetails) {
        this.commentDetails = commentDetails == null ? null : commentDetails.trim();
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }
}