package com.jk.model;

/**
 * 收货人表
 */
public class Consignee {
    /**
     * 收货人 id
     * This field corresponds to the database column t_consignee.consignee_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String consigneeId;

    /**
     * 用户id
     * This field corresponds to the database column t_consignee.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userId;

    /**
     * 收货人名称
     * This field corresponds to the database column t_consignee.consignee_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String consigneeName;

    /**
     * 联系方式
     * This field corresponds to the database column t_consignee.contact
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String contact;

    /**
     * 收货地址
     * This field corresponds to the database column t_consignee.shipping_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String shippingAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consignee.consignee_id
     *
     * @return the value of t_consignee.consignee_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getConsigneeId() {
        return consigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consignee.consignee_id
     *
     * @param consigneeId the value for t_consignee.consignee_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setConsigneeId(String consigneeId) {
        this.consigneeId = consigneeId == null ? null : consigneeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consignee.user_id
     *
     * @return the value of t_consignee.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consignee.user_id
     *
     * @param userId the value for t_consignee.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consignee.consignee_name
     *
     * @return the value of t_consignee.consignee_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consignee.consignee_name
     *
     * @param consigneeName the value for t_consignee.consignee_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consignee.contact
     *
     * @return the value of t_consignee.contact
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consignee.contact
     *
     * @param contact the value for t_consignee.contact
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consignee.shipping_address
     *
     * @return the value of t_consignee.shipping_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getShippingAddress() {
        return shippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consignee.shipping_address
     *
     * @param shippingAddress the value for t_consignee.shipping_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress == null ? null : shippingAddress.trim();
    }
}