package com.jk.model;

/**
 * 商品表  分类表   中间表
 */
public class GoodsAndType {
    /**
     * 商品表  分类表   中间表  id
     * This field corresponds to the database column t_goods_type.goods_type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsTypeId;

    /**
     * 商品表id
     * This field corresponds to the database column t_goods_type.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * 分类表id
     * This field corresponds to the database column t_goods_type.type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.goods_type_id
     *
     * @return the value of t_goods_type.goods_type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.goods_type_id
     *
     * @param goodsTypeId the value for t_goods_type.goods_type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsTypeId(String goodsTypeId) {
        this.goodsTypeId = goodsTypeId == null ? null : goodsTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.goods_id
     *
     * @return the value of t_goods_type.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.goods_id
     *
     * @param goodsId the value for t_goods_type.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.type_id
     *
     * @return the value of t_goods_type.type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.type_id
     *
     * @param typeId the value for t_goods_type.type_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }
}