package com.jk.model;

/**
 * 商品表  标签表  中间表
 */
public class GoodsAndLabel {
    /**
     * 商品表  标签表  中间表  id
     * This field corresponds to the database column t_goods_label.goods_label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsLabelId;

    /**
     * 商品表id
     * This field corresponds to the database column t_goods_label.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * 标签表 id
     * This field corresponds to the database column t_goods_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_label.goods_label_id
     *
     * @return the value of t_goods_label.goods_label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsLabelId() {
        return goodsLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_label.goods_label_id
     *
     * @param goodsLabelId the value for t_goods_label.goods_label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsLabelId(String goodsLabelId) {
        this.goodsLabelId = goodsLabelId == null ? null : goodsLabelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_label.goods_id
     *
     * @return the value of t_goods_label.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_label.goods_id
     *
     * @param goodsId the value for t_goods_label.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_label.label_id
     *
     * @return the value of t_goods_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_label.label_id
     *
     * @param labelId the value for t_goods_label.label_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId == null ? null : labelId.trim();
    }
}