package com.jk.model;

import java.util.Date;

/**
 * 退款表
 */
public class Refund {
    /**
     * 退款id
     * This field corresponds to the database column t_refund.refund_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String refundId;

    /**
     * 订单id
     * This field corresponds to the database column t_refund.indent _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String indentId;

    /**
     * 退款金额
     * This field corresponds to the database column t_refund.refund_money
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer refundMoney;

    /**
     * 申请时间
     * This field corresponds to the database column t_refund.application_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date applicationDate;

    /**
     * 退款状态(1 申请中 2 退款成功 )
     * This field corresponds to the database column t_refund.refund_state
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer refundState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund.refund_id
     *
     * @return the value of t_refund.refund_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund.refund_id
     *
     * @param refundId the value for t_refund.refund_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund.indent _id
     *
     * @return the value of t_refund.indent _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getIndentId() {
        return indentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund.indent _id
     *
     * @param indentId the value for t_refund.indent _id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setIndentId(String indentId) {
        this.indentId = indentId == null ? null : indentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund.refund_money
     *
     * @return the value of t_refund.refund_money
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund.refund_money
     *
     * @param refundMoney the value for t_refund.refund_money
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setRefundMoney(Integer refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund.application_date
     *
     * @return the value of t_refund.application_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund.application_date
     *
     * @param applicationDate the value for t_refund.application_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund.refund_state
     *
     * @return the value of t_refund.refund_state
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getRefundState() {
        return refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund.refund_state
     *
     * @param refundState the value for t_refund.refund_state
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setRefundState(Integer refundState) {
        this.refundState = refundState;
    }
}