package com.jk.model;

import java.util.Date;

/**
 * 库存表
 */
public class Stock {
    /**
     * 库存id
     * This field corresponds to the database column t_stock.stock_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String stockId;

    /**
     * 商品id
     * This field corresponds to the database column t_stock.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * 总库存
     * This field corresponds to the database column t_stock.total_inventory
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer totalInventory;

    /**
     * 可用库存
     * This field corresponds to the database column t_stock.available_stock
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer availableStock;

    /**
     * 预警数量
     * This field corresponds to the database column t_stock.warning_quantity
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer warningQuantity;

    /**
     * 入库时间
     * This field corresponds to the database column t_stock.warehousing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date warehousingTime;

    /**
     * 出库时间
     * This field corresponds to the database column t_stock.outgoing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date outgoingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.stock_id
     *
     * @return the value of t_stock.stock_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.stock_id
     *
     * @param stockId the value for t_stock.stock_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.goods_id
     *
     * @return the value of t_stock.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.goods_id
     *
     * @param goodsId the value for t_stock.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.total_inventory
     *
     * @return the value of t_stock.total_inventory
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getTotalInventory() {
        return totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.total_inventory
     *
     * @param totalInventory the value for t_stock.total_inventory
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setTotalInventory(Integer totalInventory) {
        this.totalInventory = totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.available_stock
     *
     * @return the value of t_stock.available_stock
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getAvailableStock() {
        return availableStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.available_stock
     *
     * @param availableStock the value for t_stock.available_stock
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setAvailableStock(Integer availableStock) {
        this.availableStock = availableStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.warning_quantity
     *
     * @return the value of t_stock.warning_quantity
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getWarningQuantity() {
        return warningQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.warning_quantity
     *
     * @param warningQuantity the value for t_stock.warning_quantity
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setWarningQuantity(Integer warningQuantity) {
        this.warningQuantity = warningQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.warehousing_time
     *
     * @return the value of t_stock.warehousing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getWarehousingTime() {
        return warehousingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.warehousing_time
     *
     * @param warehousingTime the value for t_stock.warehousing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setWarehousingTime(Date warehousingTime) {
        this.warehousingTime = warehousingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock.outgoing_time
     *
     * @return the value of t_stock.outgoing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getOutgoingTime() {
        return outgoingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock.outgoing_time
     *
     * @param outgoingTime the value for t_stock.outgoing_time
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setOutgoingTime(Date outgoingTime) {
        this.outgoingTime = outgoingTime;
    }
}