package com.jk.model;

/**
 * 供应商表
 */
public class Supplier {
    /**
     * 供应商id
     * This field corresponds to the database column t_supplier.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierId;

    /**
     * 供应商名称
     * This field corresponds to the database column t_supplier.supplier_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierName;

    /**
     * 供应商地址
     * This field corresponds to the database column t_supplier.supplier_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierAddress;

    /**
     * 法人代表
     * This field corresponds to the database column t_supplier.corporate_representative
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String corporateRepresentative;

    /**
     * 供应商电话
     * This field corresponds to the database column t_supplier.supplier_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_id
     *
     * @return the value of t_supplier.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_id
     *
     * @param supplierId the value for t_supplier.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_name
     *
     * @return the value of t_supplier.supplier_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_name
     *
     * @param supplierName the value for t_supplier.supplier_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_address
     *
     * @return the value of t_supplier.supplier_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_address
     *
     * @param supplierAddress the value for t_supplier.supplier_address
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress == null ? null : supplierAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.corporate_representative
     *
     * @return the value of t_supplier.corporate_representative
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getCorporateRepresentative() {
        return corporateRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.corporate_representative
     *
     * @param corporateRepresentative the value for t_supplier.corporate_representative
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setCorporateRepresentative(String corporateRepresentative) {
        this.corporateRepresentative = corporateRepresentative == null ? null : corporateRepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_phone
     *
     * @return the value of t_supplier.supplier_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_phone
     *
     * @param supplierPhone the value for t_supplier.supplier_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }
}