package com.jk.model;

/**
 * 供应商-商品中间表
 */
public class SupplierAndGoods {
    /**
     * 供应商-商品-id
     * This field corresponds to the database column t_supplier_goods.supplier_goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierGoodsId;

    /**
     * 供应商id
     * This field corresponds to the database column t_supplier_goods.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String supplierId;

    /**
     * 商品id
     * This field corresponds to the database column t_supplier_goods.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_goods.supplier_goods_id
     *
     * @return the value of t_supplier_goods.supplier_goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierGoodsId() {
        return supplierGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_goods.supplier_goods_id
     *
     * @param supplierGoodsId the value for t_supplier_goods.supplier_goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierGoodsId(String supplierGoodsId) {
        this.supplierGoodsId = supplierGoodsId == null ? null : supplierGoodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_goods.supplier_id
     *
     * @return the value of t_supplier_goods.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_goods.supplier_id
     *
     * @param supplierId the value for t_supplier_goods.supplier_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_goods.goods_id
     *
     * @return the value of t_supplier_goods.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_goods.goods_id
     *
     * @param goodsId the value for t_supplier_goods.goods_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }
}