package com.jk.model;

/**
 * 用户表
 */
public class User {
    /**
     * 用户id
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userId;

    /**
     * 用户账号
     * This field corresponds to the database column t_user.user_account
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userAccount;

    /**
     * 用户密码
     * This field corresponds to the database column t_user.user_pwd
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userPwd;

    /**
     * 用户状态( 1管理员 2 普通用户 )
     * This field corresponds to the database column t_user.user_statu
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer userStatu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_account
     *
     * @return the value of t_user.user_account
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_account
     *
     * @param userAccount the value for t_user.user_account
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_pwd
     *
     * @return the value of t_user.user_pwd
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_pwd
     *
     * @param userPwd the value for t_user.user_pwd
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_statu
     *
     * @return the value of t_user.user_statu
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getUserStatu() {
        return userStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_statu
     *
     * @param userStatu the value for t_user.user_statu
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserStatu(Integer userStatu) {
        this.userStatu = userStatu;
    }
}