package com.jk.model;

import java.util.Date;

/**
 * 用户详情表
 */
public class UserAndInfo {
    /**
     * 用户详情id
     * This field corresponds to the database column t_user_info.userinfo_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userinfoId;

    /**
     * This用户头像
     * This field corresponds to the database column t_user_info.user_photo
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userPhoto;

    /**
     * 用户名称
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userName;

    /**
     * 用户手机号
     * This field corresponds to the database column t_user_info.user_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userPhone;

    /**
     * 1普通用户   2VIP用户    3超级VIPer_info.user_level
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Integer userLevel;

    /**
     * 注册时间
     * This field corresponds to the database column t_user_info.user_creat_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private Date userCreatDate;

    /**
     * 关联表   用户表id
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userinfo_id
     *
     * @return the value of t_user_info.userinfo_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userinfo_id
     *
     * @param userinfoId the value for t_user_info.userinfo_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserinfoId(String userinfoId) {
        this.userinfoId = userinfoId == null ? null : userinfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_photo
     *
     * @return the value of t_user_info.user_photo
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_photo
     *
     * @param userPhoto the value for t_user_info.user_photo
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto == null ? null : userPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param userName the value for t_user_info.user_name
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_phone
     *
     * @return the value of t_user_info.user_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_phone
     *
     * @param userPhone the value for t_user_info.user_phone
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_level
     *
     * @return the value of t_user_info.user_level
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_level
     *
     * @param userLevel the value for t_user_info.user_level
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_creat_date
     *
     * @return the value of t_user_info.user_creat_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public Date getUserCreatDate() {
        return userCreatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_creat_date
     *
     * @param userCreatDate the value for t_user_info.user_creat_date
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserCreatDate(Date userCreatDate) {
        this.userCreatDate = userCreatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbggenerated Tue Dec 04 15:42:25 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}